// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ativos.Infrastructure.Migrations
{
    [DbContext(typeof(AtivosDbContext))]
    partial class AtivosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.21")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Ativos.Domain.Entities.Ativo", b =>
                {
                    b.Property<long>("Id_ativo")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_ativo");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_ativo"));

                    b.Property<long>("CodInventario")
                        .HasColumnType("bigint");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .HasColumnType("longtext");

                    b.Property<long>("id_localizacao")
                        .HasColumnType("bigint")
                        .HasColumnName("id_localizacao");

                    b.HasKey("Id_ativo");

                    b.HasIndex("id_localizacao");

                    b.ToTable("Ativos");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Chamado", b =>
                {
                    b.Property<long>("Id_Chamado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_chamado");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_Chamado"));

                    b.Property<long>("AtivoId_ativo")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Data_Abertura")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Descricao_Problema")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Id_Ativo")
                        .HasColumnType("bigint");

                    b.Property<int>("Status_Chamado")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Chamado");

                    b.HasIndex("AtivoId_ativo");

                    b.ToTable("Chamados");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Contrato", b =>
                {
                    b.Property<long>("Id_Contrato")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_contrato");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_Contrato"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Id_Ativo")
                        .HasColumnType("bigint");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("Valor")
                        .HasColumnType("double");

                    b.HasKey("Id_Contrato");

                    b.ToTable("Contratos");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Licenca", b =>
                {
                    b.Property<long>("Id_Licenca")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_licenca");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_Licenca"));

                    b.Property<DateTime>("Data")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nome_Soft")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Licenca");

                    b.ToTable("Licencas");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Localizacao", b =>
                {
                    b.Property<long>("Id_Localizacao")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_localizacao");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_Localizacao"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id_Localizacao");

                    b.ToTable("Localizacao");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Id_usuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id_usuario");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id_usuario"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<long>("Matricula")
                        .HasColumnType("bigint");

                    b.Property<string>("P_nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Sobrenome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("UserIdentifier")
                        .HasColumnType("char(36)");

                    b.HasKey("Id_usuario");

                    b.ToTable("Usuario");
                });

            modelBuilder.Entity("LicencaUsuario", b =>
                {
                    b.Property<long>("UsuariosId_usuario")
                        .HasColumnType("bigint");

                    b.Property<long>("licencasId_Licenca")
                        .HasColumnType("bigint");

                    b.HasKey("UsuariosId_usuario", "licencasId_Licenca");

                    b.HasIndex("licencasId_Licenca");

                    b.ToTable("LicencaUsuario");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Ativo", b =>
                {
                    b.HasOne("Ativos.Domain.Entities.Localizacao", "localizacao")
                        .WithMany("ativos")
                        .HasForeignKey("id_localizacao")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("localizacao");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Chamado", b =>
                {
                    b.HasOne("Ativos.Domain.Entities.Ativo", "Ativo")
                        .WithMany("Chamados")
                        .HasForeignKey("AtivoId_ativo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ativo");
                });

            modelBuilder.Entity("LicencaUsuario", b =>
                {
                    b.HasOne("Ativos.Domain.Entities.Usuario", null)
                        .WithMany()
                        .HasForeignKey("UsuariosId_usuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ativos.Domain.Entities.Licenca", null)
                        .WithMany()
                        .HasForeignKey("licencasId_Licenca")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Ativo", b =>
                {
                    b.Navigation("Chamados");
                });

            modelBuilder.Entity("Ativos.Domain.Entities.Localizacao", b =>
                {
                    b.Navigation("ativos");
                });
#pragma warning restore 612, 618
        }
    }
}
